
# The default www root dir to be served.
rootDir = "."

[server]
# The default server options to be modified with your preferences.
directoryListing = false
noTrailingSlash = false
virtualHosting = false
TrustProxyIp = true

[mongo]
enabled = true
uri = "mongodb://127.0.0.1:27017"
db = "vhss"
col = "logging.vhss"


[[loggers]]
enabled = true
format = "extended"
perHost = false
stdout = false
target = "logs/extended.log"
